# -*- coding: utf-8 -*-
"""Scrapping - partidos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Ij0dWqoRB0RCwsQVFflXssHwm9jF7iQ
"""

import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse, parse_qs
import base64

BASE_URL = "https://librefutboltv.su"

headers = {
    "User-Agent": "Mozilla/5.0"
}

def decode_event_link(url: str):
    """Decodifica el parámetro ?r= de un link de eventos"""
    parsed = urlparse(url)
    r_value = parse_qs(parsed.query).get("r", [""])[0]
    if r_value:
        try:
            return base64.b64decode(r_value).decode("utf-8")
        except Exception:
            return None
    return None

def scrape_agenda():
    response = requests.get(f"{BASE_URL}/agenda/", headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    partidos = soup.select("ul.menu > li")
    for partido in partidos:
        titulo = partido.find("a").get_text(" ", strip=True)
        hora = partido.find("span", class_="t").get_text(strip=True) if partido.find("span", class_="t") else ""

        if ":" in titulo:
            torneo, enfrentamiento = titulo.split(":", 1)
        else:
            torneo, enfrentamiento = "", titulo

        print(f"\n🌍 Competición: {torneo.strip()}")
        print(f"⚽ Partido: {enfrentamiento.strip()}")
        print(f"🕒 Hora: {hora}")

        # Canales
        canales = partido.select("ul li a")
        for canal in canales:
            nombre = canal.contents[0].strip()
            enlace = canal["href"]

            # Si el enlace es relativo -> completarlo
            if enlace.startswith("/"):
                enlace = BASE_URL + enlace

            # Si es /eventos/?r=..., decodificar
            if "/eventos/?" in enlace:
                real = decode_event_link(enlace)
                if real:
                    print(f"📺 Canal: {nombre} | 🔗 {real}")
                else:
                    print(f"📺 Canal: {nombre} | 🔗 {enlace} (no se pudo decodificar)")
            else:
                print(f"📺 Canal: {nombre} | 🔗 {enlace}")

        print("-" * 60)

if __name__ == "__main__":
    scrape_agenda()